### ISSUE TITLE
&apos; entities interpreted too early in attributes value

### ISSUE THREAD

**Issue by puybaret** [ndebeiss/jsXmlSaxParser#2]
Hi,

Thanks for your nice SAXParser, it works very well except for the following case:
Parsing `<test att='&apos;'/>` throws an exception "Whitespace is required between attribute-value pairs." probably because `&apos;` is converted to `'` too early.
As `<test att="&quot;"/>` is correctly parsed, I hope you can fix this issue easily.

Thanks,
Emmanuel

**Comment by ndebeiss** [comment]
Hello

Thanks for the bug report.
In the James Clark test suite : 
[040.xml](https://github.com/ndebeiss/jsXmlSaxParser/blob/master/tests/xmlconf/xmltest/valid/sa/040.xml)
and
[out/040.xml](https://github.com/ndebeiss/jsXmlSaxParser/blob/master/tests/xmlconf/xmltest/valid/sa/out/040.xml) 
the content : 
"&amp;quot;&amp;lt;&amp;amp;&amp;gt;&amp;apos;" inside an attribute value must be replaced by : "&amp;quot;&amp;lt;&amp;amp;&amp;gt;'"

It is not explained why in the W3C XML specifications, or I do not see it.
That is why that &apos; is treated differently. But I think that should not break the XML parsing.
